# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "xforge-u1604"
  config.vm.box_url = "http://linux.lsdev.sil.org/vagrant/xforge/xforge-u1604.json"
  config.vm.hostname = "vag-u1604-xf"

  config.vm.provider "virtualbox" do |vb|
    vb.name="vag-u1604-xf"
    vb.gui = true
    vb.cpus = 4
    # At least 3 GiB of RAM is needed to run tests.
    vb.memory = "4096"
    # Enable 3D acceleration and enough video RAM for larger displays.
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "shell", privileged: false, inline: <<~SHELL
    set -eux -o pipefail

    function tryharderto() { i=0; until "$@"; do ((++i > 3)) && false; echo >&2 Retrying $i; sleep 2m; done }

    # Canary
    tee ~/Desktop/development-tools/warning-not-provisioned.txt <<END
    The presence of this file means that the vagrant virtual machine did not
    finish provisioning correctly.
    The best way to get to a working machine state is to backup any data that
    you want to keep from this virtual machine, and then destroy and re-create
    this vagrant virtual machine by running these commands from your host:
        vagrant destroy
        vagrant up
    END

    GIT_USER="#{`git config --get user.name`.strip}"
    GIT_EMAIL="#{`git config --get user.email`.strip}"
    [[ -z $GIT_USER ]] || git config --global user.name "${GIT_USER}"
    [[ -z $GIT_EMAIL ]] || git config --global user.email "${GIT_EMAIL}"

    cd ~/src/web-xforge
    # Clear away some modified files. But not the whole tree in case a
    # user runs this against their data.
    git checkout -- src/SIL.XForge.Scripture/ClientApp/package{,-lock}.json || true
    git pull --ff-only --recurse-submodules

    cd ~/src/web-xforge/deploy
    tryharderto ansible-playbook playbook_bionic.yml --limit localhost

    # Remove canary
    rm ~/Desktop/development-tools/warning-not-provisioned.txt
    echo Provisioning finished successfully.
  SHELL
end
